import { GridColDef } from "@material-ui/data-grid";
import { FaPaperclip } from "react-icons/fa";

export let totalColumns: GridColDef[] = [
  {
    field: "title",
    headerName: " ",
    width: 188,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
  },
  {
    field: "tot_jobcode",
    headerName: " ",
    width: 94,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
  },
  {
    field: "tot_l_2",
    headerName: " ",
    width: 55,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
  },
  {
    field: "tot_l_3",
    headerName: " ",
    width: 55,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
  },
  {
    field: "tot_l_4",
    headerName: " ",
    width: 55,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
  },
  {
    field: "tot_depth_4",
    headerName: " ",
    width: 120,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
  },
  {
    field: "tot_classific",
    headerName: " ",
    width: 100,
    editable: true,
    sortable: false,
    disableColumnMenu: true,
    type: "editable",
  },
  {
    field: "tot_location",
    headerName: " ",
    width: 100,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
  },
  {
    field: "tot_l_3title",
    headerName: " ",
    width: 100,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
  },
  {
    field: "tot_l_4title",
    headerName: " ",
    width: 120,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
  },
  {
    field: "total",
    headerName: "Total",
    width: 75,
    editable: false,
    sortable: false,
    align: "right",
    disableColumnMenu: true,
  },
  {
    field: "day1",
    headerName: "Mon",
    width: 75,
    editable: true,
    sortable: false,
    align: "right",
    disableColumnMenu: true,
  },
  {
    field: "day2",
    headerName: "Tue",
    width: 75,
    align: "right",
    editable: true,
    sortable: false,
    disableColumnMenu: true,
  },
  {
    field: "day3",
    headerName: "Wed",
    width: 75,
    align: "right",
    editable: true,
    sortable: false,
    disableColumnMenu: true,
  },
  {
    field: "day4",
    headerName: "Thu",
    align: "right",
    width: 75,
    editable: true,
    sortable: false,
    disableColumnMenu: true,
  },
  {
    field: "day5",
    headerName: "Fri",
    width: 75,
    align: "right",
    editable: true,
    sortable: false,
    disableColumnMenu: true,
  },
  {
    field: "day6",
    headerName: "Sat",
    width: 75,
    align: "right",
    editable: true,
    sortable: false,
    disableColumnMenu: true,
  },
  {
    field: "day7",
    headerName: "Sun",
    width: 75,
    align: "right",
    editable: true,
    sortable: false,
    disableColumnMenu: true,
  },
];
export let timeSheetColumnstest: GridColDef[] = [
  {
    field: "l1",
    headerName: "Project(L1)",
    width: 138,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
    headerClassName: "",
  },
  {
    field: "jobCode",
    headerName: "Job Code",
    width: 94,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
    headerClassName: "red",
  },
  {
    field: "l2",
    headerName: "L2",
    width: 55,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
    headerClassName: "",
  },
  {
    field: "l3",
    headerName: "L3",
    width: 55,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
    headerClassName: "",
  },
  {
    field: "l4",
    headerName: "L4",
    width: 55,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
    headerClassName: "",
  },
  {
    field: "l5",
    headerName: "Dept(L5)",
    width: 120,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
    headerClassName: "",
  },
  {
    field: "classification",
    headerName: "Classific",
    width: 100,
    editable: true,
    sortable: false,
    disableColumnMenu: true,
    type: "editable",
    headerClassName: "",
  },
  {
    field: "location",
    headerName: "Location",
    width: 100,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
    headerClassName: "",
  },
  {
    field: "l3Title",
    headerName: "L3-Title",
    width: 100,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
    headerClassName: "",
  },
  {
    field: "l4Title",
    headerName: "L4-Title",
    width: 120,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
    headerClassName: "",
  },
  {
    field: "total",
    headerName: "Total",
    width: 75,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
    headerClassName: "",
  },
  {
    field: "day1",
    headerName: "21 Jun",
    width: 80,
    editable: true,
    align: "right",
    sortable: false,
    disableColumnMenu: true,
    headerClassName: "",
  },
  {
    field: "day2",
    headerName: "22 Jun",
    width: 80,
    editable: true,
    align: "right",
    sortable: false,
    disableColumnMenu: true,
    headerClassName: "",
  },
  {
    field: "day3",
    headerName: "23 Jun",
    width: 80,
    align: "right",
    editable: true,
    sortable: false,
    disableColumnMenu: true,
    headerClassName: "",
  },
  {
    field: "day4",
    headerName: "24 Jun",
    width: 80,
    align: "right",
    editable: true,
    sortable: false,
    disableColumnMenu: true,
    headerClassName: "",
  },
  {
    field: "day5",
    headerName: "25 Jun",
    width: 80,
    align: "right",
    editable: true,
    sortable: false,
    disableColumnMenu: true,
    headerClassName: "",
  },
  {
    field: "day6",
    headerName: "26 Jun",
    width: 80,
    align: "right",
    editable: true,
    sortable: false,
    disableColumnMenu: true,
    headerClassName: "",
  },
  {
    field: "day7",
    headerName: "27 Jun",
    width: 80,
    align: "right",
    editable: true,
    sortable: false,
    disableColumnMenu: true,
    headerClassName: "",
  },
];
export let timeSheetColumns: GridColDef[] = [
  {
    field: "l1",
    headerName: "Project(L1)",
    width: 138,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
    headerClassName: "",
  },
  {
    field: "jobCode",
    headerName: "Job Code",
    width: 94,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
    headerClassName: "",
  },
  {
    field: "l2",
    headerName: "L2",
    width: 55,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
    headerClassName: "",
  },
  {
    field: "l3",
    headerName: "L3",
    width: 55,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
    headerClassName: "",
  },
  {
    field: "l4",
    headerName: "L4",
    width: 55,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
    headerClassName: "",
  },
  {
    field: "l5",
    headerName: "Dept(L5)",
    width: 120,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
    headerClassName: "",
  },
  {
    field: "classification",
    headerName: "Classific",
    width: 100,
    editable: true,
    sortable: false,
    disableColumnMenu: true,
    type: "editable",
    headerClassName: "",
  },
  {
    field: "location",
    headerName: "Location",
    width: 100,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
    headerClassName: "",
  },
  {
    field: "l3Title",
    headerName: "L3-Title",
    width: 100,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
    headerClassName: "",
  },
  {
    field: "l4Title",
    headerName: "L4-Title",
    width: 120,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
    headerClassName: "",
  },
  {
    field: "total",
    headerName: "Total",
    width: 75,
    align: "right",
    editable: false,
    sortable: false,
    disableColumnMenu: true,
    headerClassName: "",
  },
  {
    field: "day1",
    headerName: "21 Jun",
    width: 80,
    editable: true,
    align: "right",
    sortable: false,
    disableColumnMenu: true,
    headerClassName: "",
  },
  {
    field: "day2",
    headerName: "22 Jun",
    width: 80,
    editable: true,
    align: "right",
    sortable: false,
    disableColumnMenu: true,
    headerClassName: "",
  },
  {
    field: "day3",
    headerName: "23 Jun",
    width: 80,
    align: "right",
    editable: true,
    sortable: false,
    disableColumnMenu: true,
    headerClassName: "",
  },
  {
    field: "day4",
    headerName: "24 Jun",
    width: 80,
    align: "right",
    editable: true,
    sortable: false,
    disableColumnMenu: true,
    headerClassName: "",
  },
  {
    field: "day5",
    headerName: "25 Jun",
    width: 80,
    align: "right",
    editable: true,
    sortable: false,
    disableColumnMenu: true,
    headerClassName: "",
  },
  {
    field: "day6",
    headerName: "26 Jun",
    width: 80,
    align: "right",
    editable: true,
    sortable: false,
    disableColumnMenu: true,
    headerClassName: "",
  },
  {
    field: "day7",
    headerName: "27 Jun",
    width: 80,
    align: "right",
    editable: true,
    sortable: false,
    disableColumnMenu: true,
    headerClassName: "",
  },
];

export let approvalColumns: GridColDef[] = [
  {
    field: "attachment",
    headerName: " ",
    width: 80,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
    renderCell: (params) => {
      // const onClick = () => {
      //   const api: any = 'test';
      //   const fields = api
      //     .getAllColumns()
      //     .map((c) => c.field)
      //     .filter((c) => c !== "__check__" && !!c);
      //   const thisRow = {};

      //   fields.forEach((f) => {
      //     thisRow[f] = params.getValue(f);
      //   });

      //   return alert(JSON.stringify(thisRow, null, 4));
      // };<div className="33

      const onClick = () => {
        alert("test");
      };

      return (
        <div onClick={onClick}>
          <FaPaperclip />
        </div>
      );
    },
  },
  {
    field: "empid",
    headerName: "Employee ID",
    width: 150,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
  },
  {
    field: "empname",
    headerName: "Employee Name",
    width: 150,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
  },
  {
    field: "sts",
    headerName: "Status",
    width: 150,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
  },
  {
    field: "type",
    headerName: "Timesheet Type",
    width: 150,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
  },
  {
    field: "pafno",
    headerName: "PAF No",
    width: 150,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
  },
  {
    field: "id",
    headerName: "1st Approver Id",
    width: 150,
    editable: true,
    sortable: false,
    disableColumnMenu: true,
    type: "editable",
  },
  {
    field: "lv1",
    headerName: "Approved Lvl1",
    width: 80,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
  },
  {
    field: "lv2",
    headerName: "Approved Lv2",
    width: 80,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
  },
  {
    field: "rejected",
    headerName: "Rejected",
    width: 80,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
  },
  {
    field: "reason",
    headerName: "Reason code",
    width: 80,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
  },
  {
    field: "total",
    headerName: "Total",
    width: 80,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
  },
];
